### ISSUE TITLE
Color is not applyed in my terminal - # Issue 002

### ISSUE THREAD

**Issue by bambou932** [bambou932OS/pyWeather#2]
I'm now using Windows 11, and it seems like my terminal doesn't have color on output.
Can you check it on Windows?

**Comment by bambou932OS** [comment]
Hello there!

Because this application using ANSI escape code, it is designed to work well on Linux.

If you using other OS, enable ANSI escape code, or use other shell or terminal that support ANSI escape code.

Check out version 2.1! I add some detail about it :)
